# Generated by Django 5.2.7 on 2025-11-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexam',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentexam',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
