# Generated by Django 4.2.26 on 2025-12-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_studentexam_finished_at_studentexam_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='marks_obtained',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
